project: https://github.com/d2jvkpn/crons
version: 0.1.1

usage: |
  crons usage...

config: |
  jobs:
  # required: name, path, cron
  - name: SLEEP
    path: sleep
    args: [70]
    working_dir: ""
    # https://crontab.guru/#30_00_*_*_1
    # At 00:30 on Monday.
    cron:
      minute: "30"
      hour: "00"
      month_day: "*"
      month: "*"
      week_day: "1"
    max_retries: 3
    start_immediately: true
