project: https://github.com/d2jvkpn/crons
version: 0.1.0

usage: |
  crons usage

config: |
  jobs:
  # required: name, path, cron
  - name: SLEEP
    path: sleep
    args: [70]
    workdir: ""
    # https://crontab.guru/#00_00_*_*_1
    cron:
      minute: "*/1"
      hour: "*"
      month_day: "*"
      month: "*"
      week_day: "*"
    max_retries: 3
    start_immediately: true
